[manifest]
version = "1.0.0"
dump_lua = true
priority = 2

# Increase highlight limit for consumables
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''for i = 1, #G.GAME.tags do
            if G.GAME.tags[i]:apply_to_run({type = 'new_blind_choice'}) then break end
          end'''
position = "at"
payload = '''        if G.GAME.selected_back.name ~= "b_SGTMD_throwback" then
        for i = 1, #G.GAME.tags do
            if G.GAME.tags[i]:apply_to_run({type = 'new_blind_choice'}) then break end
        end
    end'''
match_indent = false

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''function win_game()
    if (not G.GAME.seeded and not G.GAME.challenge) or SMODS.config.seeded_unlocks then'''
position = 'after'
payload = '''
        if G.GAME.selected_back.effect.center.calculate then G.GAME.selected_back.effect.center.calculate(G.GAME.selected_back.effect.center,nil,{win = true}) end
'''
match_indent = true